version: '3'
services:
  sapp:
    build:
      context: .
      dockerfile: Dockerfile
#    image: shahed-final-project:latest
    ports:
      - "8080:8080"
    networks:
      - shahed-final-project-network
    depends_on:
      - sdb
  sdb:
    image: postgres
    restart: unless-stopped
    networks:
      - shahed-final-project-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  shahed-final-project-network:
    driver: bridge
volumes:
  db-data:
