version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    networks:
      - shahed-final-project-network
    depends_on:
      - db
    environment:
      spring.datasource.url: ${DB_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
  db:
    image: postgres
    restart: unless-stopped
    networks:
      - shahed-final-project-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  shahed-final-project-network:
    driver: bridge

volumes:
  db-data:
